### ISSUE TITLE
What version to pick if I am using integrated graphics?

### ISSUE THREAD

**Issue by TolisKoutro** [hannesmann/vanillafixes#20]
Hello and thank you for this project!
I have a computer with amd ryzen 3 3200g with integrated graphics radeon vega 8. What version of vanillafixes do you think I should use?
Thank you.

**Comment by hannesmann** [comment]
Hey, DXVK is always recommended on AMD because it fixes a texture flickering bug that can occur with the normal AMD drivers. 

https://community.amd.com/t5/graphics/rx-580-graphical-flickering-and-stretched-textures-exclusive-to/m-p/400658/highlight/true

Vega 8 should be able to use the latest DXVK (vanillafixes-1.3-dxvk.zip) as long as your drivers are updated.

**Comment by TolisKoutro** [comment]
Perfect! Thank you so much!
