### ISSUE TITLE
character disappearing

### ISSUE THREAD

**Issue by Bazax123** [hannesmann/vanillafixes#21]
My character disappears in closed rooms, e.g. instances, buildings, under bridges. This happens when I use dxvk and when I don't use it. I tried reinstalling gpu drivers and this addon but it doesn't help.

**Comment by hannesmann** [comment]
This is a game bug that occurs if you have *too much* FPS. 

Enable V-sync or, if you're using DXVK, lock the framerate by editing dxvk.conf:
```
d3d9.maxFrameRate = 120 # or 144, 165, etc
```

**Comment by Avery1337** [comment]
Enabling V-sync worked for me.  Thanks

**Comment by andy72630** [comment]
Tho this issue was closed long ago,I investigated this further and found a working solution. The client’s WMO portal traversal can leave unit groups unclassified or test them only against an over-narrowed frustum. VanillaFixes’ high-resolution timer exposes this more frequently; quantizing the mover timer at `0x00616807` to 16 ms eliminates the symptom, but sacrifices movement smoothness and is not the proposed fix.

The working approach is to re-traverse groups known to contain units after the normal seeding pass, at depth 0 with full-screen bounds. Implementation requires hooks around `sub_682EF0`, `sub_6834E0`, and `sub_685A90`. Two important details:

- The map object is `*(a1 + 0x118)`, not `a1 + 0x94` as IDA’s pseudocode suggests.
- All previously observed groups for each unit must be retained, because an invisible unit’s current group cannot be learned through the classifier.

A/B testing consistently reproduced the bug with the fix disabled and could not reproduce it with the fix enabled, while retaining full timer precision.
