### ISSUE TITLE
Add a --custom-dll= argument to allow us to inject arbitrary mods

### ISSUE THREAD

**Issue by Zebouski** [hannesmann/vanillafixes#47]
Hi there, there's a new hackmod to 1.12 (like nampower) that is in development and testing right now, and for it to work with VF right now we had to fork and rebuild VF to hardcode the dll in to be loaded. I think it would be nice if instead we could just add an argument to call VF and have it load whatever, that would be super nice. If not, that's okay.

**Comment by hannesmann** [comment]
wowreeb already supports loading arbitrary DLLs but I agree it would be nice to have this feature in the VanillaFixes launcher. Updating the launcher is kind of a pain since it takes a few weeks for antiviruses to realize it's not a virus so I try to avoid doing it when possible.

I'll create a new release soon that supports this feature (and some other improvements). After that, I don't think I'll be updating VanillaFixes anymore, so if anyone else wants to continue development that would be fine with me. There are some feature requests/game bugs to consider (#40, #29, #27, #21, #10) and it could be nice to have a mod that puts everything in one package instead of having to use VanillaFixes, vanilla-tweaks, nampower, etc separately.

**Comment by WuVenus** [comment]
When will the new version be updated

**Comment by hannesmann** [comment]
Fixed in v1.4. I also added SuperWoWhook.dll to the list of "known" DLLs (I assume this is the fork you're talking about: https://github.com/pepopo978/vanillafixes) so it will be loaded automatically if the user has it downloaded.

**Comment by Zebouski** [comment]
Thank you! Wowreeb doesn't work on linux so I very much appreciate it.
