### ISSUE TITLE
ERROR#132

### ISSUE THREAD

**Issue by kokpk** [hannesmann/vanillafixes#57]
vanillafixes-1.4.1-dxvk Windowed Mode
![1725105906044](https://github.com/user-attachments/assets/b0192696-7892-4d0f-b07e-6eb11ddc0f47)

**Comment by jcockream** [comment]
Are you also using AutoLogin? I was having this same issue when I used AutoLogin, removed it, and the crashing went away.

**Comment by kokpk** [comment]
> Are you also using AutoLogin? I was having this same issue when I used AutoLogin, removed it, and the crashing went away.

no~

**Comment by hannesmann** [comment]
This is almost always caused by DXVK (a dialog like [this](https://raw.githubusercontent.com/hannesmann/vanillafixes/v1.4/docs/messagebox-dxvk-selftest.png) should show up). Try removing d3d9.dll to use VanillaFixes without DXVK. If it still doesn't work, it's caused by some other mod you have installed.

**Comment by Luccifer** [comment]
I deleted the dll for manymonitors from dll.txt and also used  73 KB exe download

**Comment by hannesmann** [comment]
Closing since this doesn't seem to be related to VanillaFixes.
