### ISSUE TITLE
Instructions on installing

### ISSUE THREAD

**Issue by Aztlangold** [hannesmann/vanillafixes#9]
Hello, sorry for the post if it was stated somewhere.
where does this get installed or which folder should it be placed in?

**Comment by hannesmann** [comment]
Download here: 
https://github.com/hannesmann/vanillafixes/releases/

Extract all files into your WoW folder and use VanillaFixes.exe instead of WoW.exe to launch the game. Select vanillafixes-1.2-dxvk-2.1.zip if you have a Radeon RX 400/GeForce GTX 900 or newer. If you have an older GPU use vanillafixes-1.2.zip.

**Comment by hannesmann** [comment]
Closed by #12
